### PR TITLE
Add 'The world’s easiest introduction to WebAssembly with Golang' article

### PR DESCRIPTION
**Pull request by olso**
- [x] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [x] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).

### CODE REVIEW

**Comment by olso** [comment]
Someones link is down?

**Comment by mbasso** [comment]
Hi @olso,
thank you for opening this issue, your article is awesome and I'm happy to add it to this list! 😄 
I'll just ask you if you can add the year of the article inside round brackets at the end of the link, like the others. Just to maintain the consistency of the list, because we have also links of 3 years ago...
Don't worry about the broken link, I'll check it 😄

**Comment by olso** [comment]
hi @mbasso fixed 😌

**Comment by mbasso** [comment]
Perfect! Thank you 😄

**Pull request merged**
