### PR TITLE
Added Uno Platform one-day bootcamp to the list of tutorials

### PR DESCRIPTION
**Pull request by sasakrsmanovic**
- [x] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [x] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).

### CODE REVIEW

**Comment by sasakrsmanovic** [comment]
Trying to get past the error

**Comment by sasakrsmanovic** [comment]
Hi @mbasso I'm not sure what is the current issue with the CI build for my PR, can you help me figure it out please. Also, I'd appreciate if you can review the changes. Thanks in advance.

**Comment by mbasso** [comment]
Hi @sasakrsmanovic,
thank you! I'll fix it later

**Pull request merged**
