### PR TITLE
Add four recent articles

### PR DESCRIPTION
**Pull request by JamesMilnerUK**
Added two case studies to the articles section, and two tutorials for Go and AssemblyScript respectively.

- [x] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [ ] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).

### CODE REVIEW

**Comment by JamesMilnerUK** [comment]
Looks like this is failing due to changes in links I didn't add (i.e. they are dead links). I could remove them if you like? @mbasso

**Comment by mbasso** [comment]
Hi @JamesMilnerUK,
Yeah, it would be great, thank you! 😄
Could you also add the year of the last article please?

**Comment by JamesMilnerUK** [comment]
@mbasso that's all done now. Deleted the two dead links and then updated the date for the last article I added!

**Comment by mbasso** [comment]
Perfect!
Thank you!

**Pull request merged**
