### PR TITLE
add gtree

### PR DESCRIPTION
**Pull request by ddddddO**
- [x] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [x] Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).

Web app that converts from markdown to tree using WebAssembly!
👇👇👇
web_example

site: https://ddddddo.github.io/gtree/
description: https://github.com/ddddddO/gtree#web

I would be happy to be merged👍

### CODE REVIEW

**Comment by Yee1023** [comment]
邮件我已收到，谢谢！！

**Comment by ddddddO** [comment]
@mbasso
Hi👋 I hope you can see this PR!

**Comment by mbasso** [comment]
I am sorry for the very late reply
Thank you for contributing!

**Comment by ddddddO** [comment]
Thanks for merging!

**Pull request merged**
