### PR TITLE
add Extism to non-web embedding list

### PR DESCRIPTION
**Pull request by nilslice**
repo: https://github.com/extism/extism

- [x] I've read [CONTRIBUTING.md](https://github.com/mbasso/awesome-wasm/blob/master/CONTRIBUTING.md).
- [x] (n/a) Description explains the issue / use-case resolved, and auto-closes the related issue(s) (https://help.github.com/articles/closing-issues-via-commit-messages/).

### CODE REVIEW

**Comment by nilslice** [comment]
@mbasso just checking in on this. Thanks!

**Comment by Yee1023** [comment]
邮件我已收到，谢谢！！

**Comment by mbasso** [comment]
I am sorry for the very late reply
Thank you for contributing!

**Comment by nilslice** [comment]
no problem! thank you 🙏

**Pull request merged**
